# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlertApp' do
   # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LGSideMenuControllerDemo

source 'https://github.com/CocoaPods/Specs.git'

  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'SVProgressHUD'
  pod 'RealmSwift'
  pod 'SwiftyJSON'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'ChartsRealm'
end
