# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'USGBC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for USGBC
  pod 'SwiftyPickerPopover'
  pod 'ParallaxHeader'
  pod 'SimpleImageViewer', '~> 1.1.1'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SwiftyJSON'
  pod 'Kingfisher', '~> 3.0'
  pod 'SwiftyStarRatingView'
  #pod 'TTGSnackbar'
  #pod 'Dodo', '~> 8.0'
  pod 'Firebase', '~> 4.5.0’
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  #pod 'ASHorizontalScrollView', '~> 1.5.1'
  pod 'GoogleMaps'
  pod 'PSPDFKit', podspec:'https://customers.pspdfkit.com/cocoapods/QvwdGn1azB9mw3hV4uVnXzu9sqepZk/pspdfkit/4.2.0.podspec'
  pod 'paper-onboarding', '~> 2.0.1'
  pod 'Alamofire', '~> 4.4'
  pod 'RealmSwift'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.2'
  pod 'Former'
  pod 'DLRadioButton', '~> 1.4'
  pod 'IOStickyHeader'
  pod 'SVProgressHUD'
  #pod 'CircleMenu', '~> 2.0.1'
  #pod 'Google-Maps-iOS-Utils'
  pod 'DropDown'
  #pod 'RMPZoomTransitionAnimator'
  pod 'HGPlaceholders'

  target 'USGBCTests' do
    inherit! :search_paths
    pod 'Firebase'
  end


end
